name: Terraform CI/CD

on:
  push:
    branches:
      - master
    paths:
      - 'terraform/**'
      - '**.tf'
      - '.github/workflows/**'
      - 'README.md'            # ✅ Include any file you plan to edit to trigger CI/CD
      - 'TRIGGER.md'           # (optional for dummy triggers)
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
